"use client"
import type { Metadata } from "next";
import circuit from "../../component/circuitSVG.svg"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{
        background:"rgb(241 229 160)",
        backgroundImage: `url(${circuit.src})`
      }}>{children}</body>
    </html>
  );
}
