import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import circuit from "../component/circuitSVG.svg"

export const metadata: Metadata = {
  title: "Criticador de Paginas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{
        background:"rgb(241 229 160)",
        backgroundImage: `url(${circuit.src})`
      }}>{children}</body>
    </html>
  );
}
